name: Check changes

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          enable_kvm: true

      - name: Check formatting with Denı
        run: nix run nixpkgs#deno -- fmt check **/*.md
